version: 4
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost
serial:
  port: /dev/ttyUSB0
  adapter: ember
  baudrate: 115200
  rtscts: true
advanced:
  channel: 11
  network_key: GENERATE
  pan_id: GENERATE
  ext_pan_id: GENERATE
  log_level: info
frontend:
  enabled: true
homeassistant:
  enabled: false
