version: 4
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto:1883
serial:
  port: /dev/ttyUSB0
  adapter: ember
  baudrate: 115200
  rtscts: true
advanced:
  channel: 11
  network_key: GENERATE
  pan_id: GENERATE
  ext_pan_id: GENERATE
  log_level: info
frontend:
  enabled: true
homeassistant:
  enabled: false
devices:
  '0x781c9dfffe07c6b2':
    friendly_name: 'Inspelning 1'
  '0xc02cedfffe7daa52':
    friendly_name: 'Inspelning 2'